#!/bin/sh -e
#
# Runs all application's tests.
#

# Force python2.7 for Google App Engine if available.
PYTHON="$(which python2.7 || echo -n python)"

cd tests

for test_module in *.py; do
    VKFEED_TESTS=yes PYTHONPATH=.. "$PYTHON" "$test_module"
done

